/* eslint-disable jsx-a11y/anchor-is-valid */
import './calendar.css';

const Calendar = () => {
  return (
    <template id="calendarObject">
      <header>
        <div className="header-bar" />
        <div className="header-title">
          <span align="center">
            <a className="previous round" id="previous_month">
              &#8249;
            </a>
          </span>
          <h1 id="currentMonth">December 2019</h1>
          <span align="center">
            <a className="next round" id="next_month">
              &#8250;
            </a>
          </span>
        </div>
        <div className="header-weekdays">
          <span>sun</span>
          <span>mon</span>
          <span>tue</span>
          <span>wed</span>
          <span>thu</span>
          <span>fri</span>
          <span>sat</span>
        </div>
      </header>
      <section>
        <form className="calendarForm">
          <div className="calendar">
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="last"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="current"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="next"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="next"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="next"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="next"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="next"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="next"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="next"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="next"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="next"
              date=""
              leagueDay={false}
              blackout={false}
            />
            <input
              type="checkbox"
              name=""
              id=""
              className="day"
              monthClass="next"
              date=""
              leagueDay={false}
              blackout={false}
            />
          </div>
        </form>
      </section>
    </template>
  );
};

export default Calendar;
